version: '3'
services:
  varnish:
    build: .
    ports:
    - "8000:80"
    environment:
      VARNISH_SIZE: 8g
    tmpfs:
      - /var/lib/varnish:exec
    restart: always
  tile1:
    image: maptiler/tileserver-gl
    volumes:
    - .:/data
    restart: always
  tile2:
    image: maptiler/tileserver-gl
    volumes:
    - .:/data
    restart: always
  tile3:
    image: maptiler/tileserver-gl
    volumes:
    - .:/data
    restart: always
  tile4:
    image: maptiler/tileserver-gl
    volumes:
    - .:/data
    restart: always
  tile5:
    image: maptiler/tileserver-gl
    volumes:
    - .:/data
    restart: always
  tile6:
    image: maptiler/tileserver-gl
    volumes:
    - .:/data
    restart: always
  tile7:
    image: maptiler/tileserver-gl
    volumes:
    - .:/data
    restart: always
  tile8:
    image: maptiler/tileserver-gl
    volumes:
    - .:/data
    restart: always
  tile9:
    image: maptiler/tileserver-gl
    volumes:
    - .:/data
    restart: always
  tile10:
    image: maptiler/tileserver-gl
    volumes:
    - .:/data
    restart: always
